name: Continuous Integration

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Login to Registry
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.repository }} --password-stdin
      - name: Build Image
        run: |
          make build
      - name: Push Image
        run: |
          make push