name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: docker

    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Build Image
        run: |
          make build